config/routes.rb
Politiwiki::Application.routes.draw do
  resources :wikis 
  resources :collaborators
    

  devise_for :users
  
  get 'free' => 'welcome#free'
  get 'premium' => 'welcome#premium'

  root :to => "welcome#index"
  

end

app/models/collaborators.rb
class Collaborators < ActiveRecord::Base
  has_and_belongs_to_many :wikis, through: :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_and_belongs_to_many :wikis
   has_and_belongs_to_many :collaborators


end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :collaborators

  default_scope { order('created_at DESC')}

  scope :visible_to, where( public: true)

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collaborator_controller.rb
class CollaboratorController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #authenticates user as first action, responds to JSON to interact with API's
  before_filter :authenticate_user!
  respond_to :json

  def edit
    #defines the user as the current logged-in user. 
    @user = current_user
  end

  def update_password
    #finds current user by their id, updates using devise .update_with_password() method
    # redirects to previous page. 
    @user = User.find(current_user.id)
    if @user.update_with_password(user_params)

      sign_in @user, :bypass => true
      redirect_to root_path 
    else
      render "edit"
    end
  end
 
  def show
    @user = User.find(params[:id])
    
  end

  def update
    # if the user data is update notice is flashed, and then redirects user to edit page. 
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path(current_user)
    else
      render "devise/registrations/edit"
    end
  end
 
   private
    # private method to keep things RESTful and not repeat code. 
   def user_params
     params.require(:user).permit(:name, :password, :current_password, :password_confirmation)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def free
  end

  def premium
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  def index
    @wikis = current_user.wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def show
    @wikis = Wiki.find(params[:id])
  end

  def create
    @wiki = current_user.wiki.build(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def collaborators
    @collaborators = Collaborators.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collaborator_helper.rb
module CollaboratorHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= favicon_link_tag 'favicon.ico' %>
<head>
<script src="epiceditor.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Politiwiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
       <ul class="nav nav-tabs">
        <li><%= link_to "Politiwiki", root_path %></li>
        <li><%= link_to "Free", free_path %></li>
        <li><%= link_to "Premium", premium_path %></li>
        <li><%= link_to "Wikis", wikis_path %>
          <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
      </ul>
      <% if flash[:notice] %>
      <% end %>
<%= yield %>
  </div>
</body>
</html>

app/views/welcome/free.html.erb
<br/>
<div class="page-header">
<h2 align="center">Create Custom Wikis for Free!</h1>
<br/>
<p>Politiwiki aims to be simple and useful. A platform agnostic service, available anytime you have a connection to the net. </p>
<br/>
<p> Create a community around important information. Collaborate with other users, and do so without spending a cent. 
<br/>
<br/>
<h2> Inform, Include, Influence </h2> </p>
<p> --your dev, <a href="mailto:christopher@scratchitoff.co"> Christopher </a> </p>

</div>

app/views/welcome/index.html.erb
<br/>
<div class="page-header">
  <p class="lead">Politiwiki</p>
  <p>Share information, create community!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Inform.</h2>
    <p>Use Politiwiki to share information about the politicians that matter to you. Let's keep folk honest. </p>
  </div>
  <div class="col-md-4">
    <h2>Include.</h2>
    <p>Invite collaborators to help curate your information. Learned collaborators make for information-based communities.</p>
  </div>
  <div class="col-md-4">
    <h2>Influence.</h2>
    <p>Politicians like to control the way information is "spun". With Politiwiki, you can cut through the spin to get real information to the right people: the voters. </p>
  </div>
</div>

app/views/welcome/premium.html.erb
<br/>
<div class="jumbotron">
<h2 align="center"> Create Private Wikis</h1>
<br/>
<p>Politiwiki aims to be simple and useful. A platform agnostic service, available anytime you have a connection to the net. </p>
<br/>
<p> As a Premium user, you can create private wikis. Use your wiki to collaborate with your team, with friends or family. Wikis are a great way to curate information! 
<br/>
<br/>
<h2> Inform, Include, Influence </h2> </p>
<p> --your dev, <a href="mailto:christopher@scratchitoff.co"> Christopher </a> </p>
</div>

app/views/wikis/collaborators.html.erb
<h1>Wiki#collaborators</h1>
<p>Find me in app/views/wiki/collaborators.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Wiki#edit</h1>
<p>Find me in app/views/wiki/edit.html.erb</p>

app/views/wikis/index.html.erb
<h1>Your Wikis</h1>

<div class="row">
  <div class="col-md-8">
  </br>
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.name, wiki %>
          </h4>

        </div>
      </div>
    <% end %>
    
  </div>
  <div class="col-md-4">
    <% if policy(Wiki.new).create? %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success btn-lg' %>
    <% end %>
  </div>
</div>
    

app/views/wikis/new.html.erb
<h1> New Wiki </h1>

<div class="row"<
  <div class="col-md-4">
    <p> Creating a new Wiki </p>
      <ul>
        <li> Use markdown to style your Wiki. </li>
        <li> Include accurate information, and link to references. </li>
        <li> Controversy is only a problem when information isn't accurate. </li>
        <li> Invite collaborators who can help curate the information. </li>
      </ul>
  </div>
      <div class="col-md-8">
        <%= simple_form_for @wiki do |f| %>
          <%= f.input :title, label: 'Enter your wikis title here' %>
          <div id="epiceditor"> <%= f.input :body, label: 'Enter your information here' %><script type="text/javascript"> var editor = new EpicEditor().load();</script></div>
          <%= f.button :submit, label: 'Save' %>
        <% end %>
      </div>
</div>      

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<p><%= @wiki.body %></p>